// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    mainSidebar: [{ type: "autogenerated", dirName: "." }],
    vision: [
        {
            type: "category",
            label: "Vision",
            collapsed: false,
            items: [
                {
                    type: "doc",
                    id: "vision/data",
                },
                {
                    type: "doc",
                    id: "vision/mission",
                },
                {
                    type: "doc",
                    id: "vision/values",
                },
                {
                    type: "doc",
                    id: "vision/dna",
                },
                {
                    type: "doc",
                    id: "vision/readings",
                },
            ],
        },
    ],

    organization: [
        {
            type: "category",
            label: "Organization",
            collapsed: false,
            items: [
                {
                    type: "doc",
                    id: "organization/team",
                },
                {
                    type: "doc",
                    id: "organization/offices",
                },
                {
                    type: "doc",
                    id: "organization/work-hours",
                },
                {
                    type: "doc",
                    id: "organization/social-media",
                },
            ],
        },
    ],
    process: [
        {
            type: "category",
            label: "Process & Rituals",
            collapsed: false,
            items: [
                {
                    type: "doc",
                    id: "process/agility",
                },
                {
                    type: "doc",
                    id: "process/kanban",
                },
                {
                    type: "doc",
                    id: "process/rituals",
                },
                {
                    type: "doc",
                    id: "process/recruitment",
                },
                {
                    type: "doc",
                    id: "process/tools",
                },
            ],
        },
    ],
    dev: [
        {
            type: "category",
            label: "Dev Wiki",
            collapsed: false,
            items: [
                {
                    type: "doc",
                    id: "dev/dev-home",
                },
                {
                    type: "doc",
                    id: "dev/what-should-i-know",
                },
                {
                    type: "doc",
                    id: "dev/open-source",
                },
                {
                    type: "doc",
                    id: "dev/github-flow",
                },
                {
                    type: "doc",
                    id: "dev/naming-rules",
                },
                {
                    type: "doc",
                    id: "dev/ci-cd",
                },
                {
                    type: "doc",
                    id: "dev/signing-commits",
                },
                {
                    type: "doc",
                    id: "dev/vs-extensions",
                },
            ],
        },
    ],
};

module.exports = sidebars;
