// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    mainSidebar: [{ type: "autogenerated", dirName: "." }],
    vision: [
        {
            type: "category",
            label: "Vision",
            collapsed: false,
            items: [
                {
                    type: "doc",
                    id: "vision/data",
                },
                {
                    type: "doc",
                    id: "vision/mission",
                },
                {
                    type: "doc",
                    id: "vision/values",
                },
                {
                    type: "doc",
                    id: "vision/dna",
                },
                {
                    type: "doc",
                    id: "vision/readings",
                },
            ],
        },
    ],

    organization: [
        {
            type: "category",
            label: "Organization",
            collapsed: false,
            items: [
                {
                    type: "doc",
                    id: "organization/team",
                },
                {
                    type: "doc",
                    id: "organization/offices",
                },
                {
                    type: "doc",
                    id: "organization/work-hours",
                },
                {
                    type: "doc",
                    id: "organization/social-media",
                },
            ],
        },
    ],
    process: [
        {
            type: "category",
            label: "Process & Rituals",
            collapsed: false,
            items: [
                {
                    type: "doc",
                    id: "process/agility",
                },
                {
                    type: "doc",
                    id: "process/rituals",
                },
                {
                    type: "doc",
                    id: "process/recruitment",
                },
                {
                    type: "doc",
                    id: "process/tools",
                },
            ],
        },
    ],
    employees: [
        {
            type: "link",
            label: "Organigram",
            href: "https://okp4.ilucca.net/directory/users/organization-chart",
        },
        {
            type: "category",
            label: "Employees benefits",
            link: {
                type: "doc",
                id: "employees/benefits",
            },
            items: [
                {
                    type: "doc",
                    id: "employees/benefits/phone",
                },
                {
                    type: "doc",
                    id: "employees/benefits/luncheon-voucher",
                },
                {
                    type: "doc",
                    id: "employees/benefits/bspce",
                },
                {
                    type: "doc",
                    id: "employees/benefits/tokens",
                },
                {
                    type: "doc",
                    id: "employees/benefits/sustainable-mobility",
                },
                {
                    type: "doc",
                    id: "employees/benefits/remote-work",
                },
                {
                    type: "doc",
                    id: "employees/benefits/offices",
                },
            ],
        },
        {
            type: "category",
            label: "Tools",
            link: {
                type: "doc",
                id: "employees/tools",
            },
            items: [
                {
                    type: "doc",
                    id: "employees/tools/mail-agenda",
                },
                {
                    type: "doc",
                    id: "employees/tools/nextcloud",
                },
                {
                    type: "doc",
                    id: "employees/tools/github",
                },
                {
                    type: "doc",
                    id: "employees/tools/lucca",
                },
                {
                    type: "doc",
                    id: "employees/tools/slack",
                },
                {
                    type: "doc",
                    id: "employees/tools/okp4-graphic-charter",
                },
            ],
        },
        {
            type: "doc",
            id: "employees/reviews-and-seminars",
            label: "Reviews and seminars",
        },
        {
            type: "doc",
            id: "employees/travel-policy",
            label: "Travel policy",
        },
        {
            type: "doc",
            id: "employees/recruitment",
            label: "Recruitment",
        },
    ],
};

module.exports = sidebars;
